### ISSUE TITLE
Quick claim button

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#277]
To claim materials is a bit tricky, I think we can simplify the process by having a button (somewhere on the page) that prefill the litigation form.
![image](https://user-images.githubusercontent.com/598726/213896946-5976f55f-6b5a-4c2a-a493-48e463567c58.png)

- [x] 1. The claim button should redirect to the create litigation page. The litigation form should be pre filled with the material/creation data
- [x] 2. Only show the 'Claim' button for materials/creations that are not already claimed. We have a flag `is_claimed` for material and creation to check for this. Example: `material.is_claimed`

**Comment by UmairMukhtar** [comment]
![Screenshot from 2023-02-17 19-24-20](https://user-images.githubusercontent.com/34018917/219681393-aff23365-8666-4ef5-a814-94f55da25048.png)
@huzaifa-99 @AltiMario how about we display an separate text box in case of quick claim , and fetch all the information related to material on the background?
Because there is not point of displaying the materials dropdown list to user as he already decided which material to claim by clicking on it

**Comment by UmairMukhtar** [comment]
https://user-images.githubusercontent.com/34018917/219842793-e10e1c75-d0bd-4729-be4b-599319547a58.mp4

**Comment by AltiMario** [comment]
I would like to have a full link instead of just the ID
https://github.com/eLearningDAO/POCRE/pull/310#issuecomment-1435668030

**Comment by UmairMukhtar** [comment]
> I would like to have a full link instead of just the ID [#310 (comment)](https://github.com/eLearningDAO/POCRE/pull/310#issuecomment-1435668030)

done

**Comment by UmairMukhtar** [comment]
Fixed in pull 
https://github.com/eLearningDAO/POCRE/pull/310
